apiVersion: apps/v1
kind: Deployment
metadata:
  name: prms-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prms-php
  template:
    metadata:
      labels:
        app: prms-php
    spec:
      containers:
        - name: prms-php
          image: prms-php:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: prms-php-config
              mountPath: /usr/local/etc/php/conf.d/custom.ini
              subPath: custom.ini
            - name: prms-php-mysql-config
              mountPath: /var/www/html/app/Configs/MysqlConfig.php
              subPath: MysqlConfig.php
            - name: db-backups
              mountPath: /var/www/html/storage/DbBackups
      volumes:
        - name: prms-php-config
          configMap:
            name: prms-php-config
        - name: prms-php-mysql-config
          configMap:
            name: prms-php-mysql-config
        - name: db-backups
          hostPath:
            path: /Users/hailongxy/Documents/var/www/prms/php/storage/DbBackups
            type: DirectoryOrCreate
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prms-php-config
data:
  custom.ini: |
    upload_max_filesize = 64
    post_max_size = 64M
    memory_limit = 256M
---
apiVersion: v1
kind: Service
metadata:
  name: prms-php-service
spec:
  type: ClusterIP
  selector:
    app: prms-php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prms-php-mysql-config
data:
  MysqlConfig.php: |
    <?php
    namespace App\Configs;

    class MysqlConfig
    {
        private $props = [
            'host' => 'mysql',
            'port' => 3306,
            'user' => 'root',
            'password' => 'ServBay.dev',
            'database' => 'prms',
            'exportPath' => __DIR__.'/../../storage/DbBackups'
        ];
        private static $instance;

        private function __construct()
        {
        }

        public static function getInstance(){
            if (empty(self::$instance)){
                self::$instance = new MysqlConfig();
            }
            return self::$instance;
        }


        public function getProperty(string $key): string
        {
            return $this->props[$key];
        }
    }